# Site settings
title: Nim
description: >
  The Nim programming language is a concise, fast programming language that
  compiles to C, C++ and JavaScript.
baseurl: ""

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
sass:
  style: compressed
exclude:
  - CNAME
  - README.md
  - LICENSE.md

  